openapi: 3.0.0
info:
  title: synergi
  version: 1.0.0
servers:
  - url: 'https://{{dev}}.execute-api.us-east-1.amazonaws.com'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: segment
  - name: Offer
  - name: Intregrations
  - name: campaigns
paths:
  /v1/get_historical_event_data:
    get:
      tags:
        - campaigns
      summary: get_historical_event_data
      parameters:
        - name: parameter
          in: query
          schema:
            type: string
          example: campaign
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/get_all_ai_created_segments_or_offers:
    get:
      tags:
        - Offer
      summary: get_all_ai_created_offers
      parameters:
        - name: event_type
          in: query
          schema:
            type: string
          example: offer
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/segment_offer_ai_create_v2:
    post:
      tags:
        - Offer
      summary: Purchase FHA
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                event_id: 'ai#offer#1695932043210886da790df8f9e6b42417400f45424f6090'
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/segment_offer_source_config:
    get:
      tags:
        - Offer
      summary: copy edit offer
      parameters:
        - name: source
          in: query
          schema:
            type: string
          example: RateSheet
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/segment_offer_source_total_records:
    get:
      tags:
        - Offer
      summary: get target Purchase FHA
      parameters:
        - name: where_condition
          in: query
          schema:
            type: string
          example: (NEW_LOAN_PURPOSE == 'P' && NEW_TERM == 360)
        - name: sql_where_condition
          in: query
          schema:
            type: string
          example: (NEW_LOAN_PURPOSE = 'P' AND NEW_TERM = 360)
        - name: source
          in: query
          schema:
            type: string
          example: SNG_PRCNG_OUTPUT
        - name: entity_type
          in: query
          schema:
            type: string
          example: offer
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/segment_offer_create:
    post:
      tags:
        - Offer
      summary: review copy offer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                json_where_condition:
                  and:
                    - ==:
                        - var: NEW_LOAN_PURPOSE
                        - P
                    - ==:
                        - var: NEW_TERM
                        - 360
                where_condition: (NEW_LOAN_PURPOSE == 'P' && NEW_TERM == 360)
                sql_where_condition: (NEW_LOAN_PURPOSE = 'P' AND NEW_TERM = 360)
                source: RateSheet
                entity_type: offer
                name: '{{rndname}}'
                description: >-
                  Pricing Engine based offers. They apply your rate data to your
                  list and generate personalized scenarios for borrower
                  engagment.
                total_records: 1602
                process_type: copy
                dateTime: {}
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/segment_offer_save:
    post:
      tags:
        - Offer
      summary: save copy offer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                pk: '{{offer_pk}}'
                sk: '{{offer_sk}}'
                entity_type: offer
                process_type: copy
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/delete_item:
    delete:
      tags:
        - Offer
      summary: delete offer
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/segment_offer_custom_get_info:
    get:
      tags:
        - Offer
      summary: copy offer
      parameters:
        - name: pk
          in: query
          schema:
            type: string
          example: '''{{offer_pk}}'''
        - name: sk
          in: query
          schema:
            type: string
          example: '''{{offer_sk}}'''
        - name: entity_type
          in: query
          schema:
            type: string
          example: offer
        - name: process_type
          in: query
          schema:
            type: string
          example: copy
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/mapping_tables:
    get:
      tags:
        - Intregrations
      summary: date import
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/get_document_file_upload_s3_presigned_url:
    get:
      tags:
        - Intregrations
      summary: agree and upload
      parameters:
        - name: file_name
          in: query
          schema:
            type: string
          example: LOAN SAMPLE (822).csv
        - name: server_table
          in: query
          schema:
            type: string
          example: Chat_Logs
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/document_create:
    post:
      tags:
        - Intregrations
      summary: document create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                uploadFileName: >-
                  LOANSAMPLE822csvdocument1702032343167298818b560e0ae04a5fc3d9e4b8192911ba5.csv
                importName: test 5341
                uploadType: Chat_Logs
                description: test......
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/document_mapping_and_restore:
    post:
      tags:
        - Intregrations
      summary: document_mapping_and_restore
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                document_id: 'document#Chat_Logs_temp'
                mapped_document:
                  index: Agent ID who responded
                  UNIQUE_ID: Chat End Date Time
                  CURRENT_FICO_PRIM: ''
                  PROP_STATE: ''
                  PROP_ZIP: ''
                  UNPAID_BALANCE: ''
                  INTEREST_RATE: ''
                  PRINCIPAL_AND_INTEREST: ''
                  MI_AMT: ''
                  LOAN_TYPE: ''
                  LOAN_TERM: ''
                  ORIGINATION_DATE: ''
                  REMAINING_TERM: ''
                  ORIG_HELOC_BALANCE: ''
                  CURRENT_PROPERTY_VALUE: ''
                  LTV: ''
                  PROPERTY_TYPE: ''
                  CURRENT_OCCUPANCY_TYPE: ''
                  NUMBER_OF_UNITS: ''
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/document_update_with_selected_channels:
    post:
      tags:
        - Intregrations
      summary: document_update_with_selected_channels
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                document_id: 'document#Chat_Logs_temp'
                selected_channels: []
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/is_user_capable_to_create_campaign:
    get:
      tags:
        - campaigns
      summary: is_user_capable_to_create_campaign
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/get_campaign_objective_channel_vendors:
    get:
      tags:
        - campaigns
      summary: create new campaigns
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/create_campaign_id:
    post:
      tags:
        - campaigns
      summary: create_campaign_id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: '{{rndname}}'
                objective: Awarness
                selected_channel_vendors:
                  - channel: Email
                    vendors:
                      - Adobe
                description: test.........
                channel_type: manual
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/campaign_related_sources:
    get:
      tags:
        - campaigns
      summary: campaign_related_sources?parameter=segment
      parameters:
        - name: parameter
          in: query
          schema:
            type: string
          example: segment
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/campaign_ai_segments:
    get:
      tags:
        - campaigns
      summary: campaign_ai_segments
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/add_data_source_or_segment_2_campaign:
    post:
      tags:
        - campaigns
      summary: add_data_source_or_segment_2_campaign
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                segments:
                  - name: Upgrader-Cashout1747
                    segment_pk: 'segment#upgrader-cashout1747'
                    segment_sk: 'segment#17018663455989084aba2ecdc2f1ddd7f1339dff8aee0187c'
                segments_type: manual
                campaign_pk: '{{campaign_pk}}'
                campaign_sk: '{{campaign_sk}}'
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/segment_multiple_offers:
    get:
      tags:
        - campaigns
      summary: segment_multiple_offers
      parameters:
        - name: campaign_pk
          in: query
          schema:
            type: string
          example: '{{campaign_pk}}'
        - name: campaign_sk
          in: query
          schema:
            type: string
          example: '{{campaign_sk}}'
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/campaign_add_segment_offers:
    post:
      tags:
        - campaigns
      summary: campaign_add_segment_offers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                campaign_pk: '{{campaign_pk}}'
                campaign_sk: '{{campaign_sk}}'
                channel_segment_offer:
                  - channel: Email
                    segment_offers:
                      - segment_name: Upgrader-Cashout1747
                        segment_pk: 'segment#upgrader-cashout1747'
                        segment_sk: >-
                          segment#17018663455989084aba2ecdc2f1ddd7f1339dff8aee0187c
                        segment_start_datetime: '2023-12-08 17:04'
                        segment_end_datetime: ' '
                        segment_min_budget: ''
                        segment_max_budget: ''
                        segment_budget_type: daily
                        segment_no_limit: true
                        segment_batch_size: ''
                        segment_batch_type: daily
                        offers:
                          - offer_name: Rate Term PI Benefit 1
                            offer_sk: >-
                              offer#1701860468650535860bf5de82712db4884280d349cb7c566
                            offer_pk: 'offer#rate term pi benefit 1'
                            offer_segment_count: 8
                            template_pk: '8954253947521835103'
                            template_sk: '8954253947521835103'
                            template_name: Adobe Creative Suite
                    total_offers: 1
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
  /v1/campaign_confirm:
    post:
      tags:
        - campaigns
      summary: campaign_confirm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                campaign_pk: '{{campaign_pk}}'
                campaign_sk: '{{campaign_sk}}'
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Access token is missing
        '500':
          description: Internal Server Error
          content:
            application/json: {}
